# Generated by Django 3.0.5 on 2020-05-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Temperature_dashboard', '0002_auto_20200501_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={},
        ),
        migrations.AlterModelTable(
            name='temperature',
            table=None,
        ),
    ]
